### ISSUE TITLE
How do I change the size of texts on webpages?

### ISSUE THREAD

**Issue by acadTags** [randal-sean-harrison/academic-website-template#1]
Nice website! 

I tried to change the xx rem in .css files, but could not change the size of texts on the webpage. Would you help sort this out?

Many thanks,
Hang

**Comment by randal-sean-harrison** [comment]
Within the first 49 lines of the "css/custom.css" file, you'll find the declarations for the base size of the font and font sizes for headers, p, li, etc. -- all the element sizes are there. Just change 1rem to 1.3 rem (to increase), or even to an absolute value like 16px, say.

**Comment by acadTags** [comment]
> Within the first 49 lines of the "css/custom.css" file, you'll find the declarations for the base size of the font and font sizes for headers, p, li, etc. -- all the element sizes are there. Just change 1rem to 1.3 rem (to increase), or even to an absolute value like 16px, say.

I just tried this, but it seems do not work. For example, change the line 6, line 10 or line 16-21, then you refresh the webpage, all still remain the same. Any procedure wrong?

Thanks.

**Comment by randal-sean-harrison** [comment]
Try setting the base font on HTML to 16px. Or try setting them to exact numvers. Here’s a pretty standard typographic hierarchic scale. 

h1 { font-size: 64px }
h2 { font-size: 47.5px }
h3 { font-size: 32px }
h4 { font-size: 23.75px }
 
p { font-size: 16px }
 
small { font-size: 8px }

best,
Randy
……

Randal Sean Harrison, Ph.D.
Emerging Technologies Librarian

University of Notre Dame
158 Hesburgh Library
Notre Dame, IN 46556

(574) 631-0312
rharriso@nd.edu <mailto:rharriso@nd.edu>
randalseanharrison.com <http://www.randalseanharrison.com/>

⌖  Map to my office <http://randalseanharrison.com/new_office/map.png>
⌖  Make a meeting <https://randalseanharrison.youcanbook.me/>
 <http://randalseanharrison.com/new_office/map.png>

**Comment by acadTags** [comment]
Thank you Randy.

I followed these changes, but all still remain the same on the webpage. Any ideas?...

Best wishes,
Hang

**Comment by randal-sean-harrison** [comment]
Yeah, I need to see what you’re looking at. Can you provide more information? 

best,
Randy
……

Randal Sean Harrison, Ph.D.
Emerging Technologies Librarian

University of Notre Dame
158 Hesburgh Library
Notre Dame, IN 46556

(574) 631-0312
rharriso@nd.edu <mailto:rharriso@nd.edu>
randalseanharrison.com <http://www.randalseanharrison.com/>

⌖  Map to my office <http://randalseanharrison.com/new_office/map.png>
⌖  Make a meeting <https://randalseanharrison.youcanbook.me/>
 <http://randalseanharrison.com/new_office/map.png>

**Comment by acadTags** [comment]
Thanks. I just want to make all texts slightly smaller on my webpage.

I find changing the base font on HTML to 16px works, but only on the Microsoft Edge, but not on the Google Chrome on my PC. Maybe Chrome stored the old .css file?

-----

Update: Now it also works on my Chrome... Thanks! It just can take 3 refreshes to affect.

Best wishes,
Hang

**Comment by randal-sean-harrison** [comment]
Hi Hang,
In preparation for my workshop on this, each semester, I've updated the website from scratch. I daresay you shouldn't have the font issue anymore, as the codebase is entirely new and the font issue seems to be resolved.
